services:
  menav:
    container_name: menav
    image: menav:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MENAV_ENABLE_SYNC: ${MENAV_ENABLE_SYNC:-false}
        MENAV_IMPORT_BOOKMARKS: ${MENAV_IMPORT_BOOKMARKS:-false}
    ports:
      - '${MENAV_PORT:-8080}:80'
    restart: unless-stopped
